const PACK_LOGOS = {
    "Power Keepers":  "https://images.pokemontcg.io/ex16/logo.png",
    "Unified Minds":  "https://images.pokemontcg.io/sm11/logo.png",
    "Next Destinies":  "https://images.pokemontcg.io/bw4/logo.png",
    "Dark Explorers":  "https://images.pokemontcg.io/bw5/logo.png",
    "Evolutions":  "https://images.pokemontcg.io/xy12/logo.png",
    "Secret Wonders":  "https://images.pokemontcg.io/dp3/logo.png",
    "Plasma Storm":  "https://images.pokemontcg.io/bw8/logo.png",
    "Jungle":  "https://images.pokemontcg.io/base2/logo.png",
    "Shining Legends":  "https://images.pokemontcg.io/sm35/logo.png",
    "Nintendo Black Star Promos":  "https://images.pokemontcg.io/np/logo.png",
    "Noble Victories":  "https://images.pokemontcg.io/bw3/logo.png",
    "Boundaries Crossed":  "https://images.pokemontcg.io/bw7/logo.png",
    "Plasma Freeze":  "https://images.pokemontcg.io/bw9/logo.png",
    "Dragon":  "https://images.pokemontcg.io/ex3/logo.png",
    "POP Series 8":  "https://images.pokemontcg.io/pop8/logo.png",
    "HeartGold \u0026 SoulSilver":  "https://images.pokemontcg.io/hgss1/logo.png",
    "Neo Discovery":  "https://images.pokemontcg.io/neo2/logo.png",
    "Astral Radiance Trainer Gallery":  "https://images.pokemontcg.io/swsh10tg/logo.png",
    "Steam Siege":  "https://images.pokemontcg.io/xy11/logo.png",
    "Paldean Fates":  "https://images.pokemontcg.io/sv4pt5/logo.png",
    "Dragons Exalted":  "https://images.pokemontcg.io/bw6/logo.png",
    "Base Set 2":  "https://images.pokemontcg.io/base4/logo.png",
    "Legend Maker":  "https://images.pokemontcg.io/ex12/logo.png",
    "McDonald\u0027s Collection 2012":  "https://images.pokemontcg.io/mcd12/logo.png",
    "XY Black Star Promos":  "https://images.pokemontcg.io/xyp/logo.png",
    "Team Magma vs Team Aqua":  "https://images.pokemontcg.io/ex4/logo.png",
    "McDonald\u0027s Collection 2022":  "https://images.pokemontcg.io/mcd22/logo.png",
    "Gym Challenge":  "https://images.pokemontcg.io/gym2/logo.png",
    "Dragon Vault":  "https://images.pokemontcg.io/dv1/logo.png",
    "Rising Rivals":  "https://images.pokemontcg.io/pl2/logo.png",
    "Celebrations: Classic Collection":  "https://images.pokemontcg.io/cel25c/logo.png",
    "Burning Shadows":  "https://images.pokemontcg.io/sm3/logo.png",
    "McDonald\u0027s Collection 2014":  "https://images.pokemontcg.io/mcd14/logo.png",
    "Destined Rivals":  "https://images.pokemontcg.io/sv10/logo.png",
    "Phantasmal Flames":  "https://images.pokemontcg.io/me2/logo.png",
    "Celebrations":  "https://images.pokemontcg.io/cel25/logo.png",
    "McDonald\u0027s Collection 2018":  "https://images.pokemontcg.io/mcd18/logo.png",
    "Call of Legends":  "https://images.pokemontcg.io/col1/logo.png",
    "XY":  "https://images.pokemontcg.io/xy1/logo.png",
    "Ruby \u0026 Sapphire":  "https://images.pokemontcg.io/ex1/logo.png",
    "BREAKpoint":  "https://images.pokemontcg.io/xy9/logo.png",
    "EX Trainer Kit 2 Plusle":  "https://images.pokemontcg.io/tk2a/logo.png",
    "Chaos Rising":  "https://images.scrydex.com/pokemon/me4-logo/logo",
    "Paradox Rift":  "https://images.pokemontcg.io/sv4/logo.png",
    "Furious Fists":  "https://images.pokemontcg.io/xy3/logo.png",
    "Twilight Masquerade":  "https://images.pokemontcg.io/sv6/logo.png",
    "Scarlet \u0026 Violet Black Star Promos":  "https://images.pokemontcg.io/svp/logo.png",
    "Best of Game":  "https://images.pokemontcg.io/bp/logo.png",
    "Lost Origin":  "https://images.pokemontcg.io/swsh11/logo.png",
    "Expedition Base Set":  "https://images.pokemontcg.io/ecard1/logo.png",
    "Neo Destiny":  "https://images.pokemontcg.io/neo4/logo.png",
    "BW Black Star Promos":  "https://images.pokemontcg.io/bwp/logo.png",
    "Roaring Skies":  "https://images.pokemontcg.io/xy6/logo.png",
    "Evolving Skies":  "https://images.pokemontcg.io/swsh7/logo.png",
    "Pokémon Rumble":  "https://images.pokemontcg.io/ru1/logo.png",
    "Surging Sparks":  "https://images.pokemontcg.io/sv8/logo.png",
    "HS—Triumphant":  "https://images.pokemontcg.io/hgss4/logo.png",
    "Southern Islands":  "https://images.pokemontcg.io/si1/logo.png",
    "EX Trainer Kit Latios":  "https://images.pokemontcg.io/tk1b/logo.png",
    "POP Series 1":  "https://images.pokemontcg.io/pop1/logo.png",
    "Champion\u0027s Path":  "https://images.pokemontcg.io/swsh35/logo.png",
    "Paldea Evolved":  "https://images.pokemontcg.io/sv2/logo.png",
    "Plasma Blast":  "https://images.pokemontcg.io/bw10/logo.png",
    "Wizards Black Star Promos":  "https://images.pokemontcg.io/basep/logo.png",
    "Stellar Crown":  "https://images.pokemontcg.io/sv7/logo.png",
    "Team Up":  "https://images.pokemontcg.io/sm9/logo.png",
    "Vivid Voltage":  "https://images.pokemontcg.io/swsh4/logo.png",
    "Detective Pikachu":  "https://images.pokemontcg.io/det1/logo.png",
    "Double Crisis":  "https://images.pokemontcg.io/dc1/logo.png",
    "POP Series 3":  "https://images.pokemontcg.io/pop3/logo.png",
    "FireRed \u0026 LeafGreen":  "https://images.pokemontcg.io/ex6/logo.png",
    "Obsidian Flames":  "https://images.pokemontcg.io/sv3/logo.png",
    "Ancient Origins":  "https://images.pokemontcg.io/xy7/logo.png",
    "Sword \u0026 Shield":  "https://images.pokemontcg.io/swsh1/logo.png",
    "Black \u0026 White":  "https://images.pokemontcg.io/bw1/logo.png",
    "McDonald\u0027s Collection 2017":  "https://images.pokemontcg.io/mcd17/logo.png",
    "Crown Zenith Galarian Gallery":  "https://images.pokemontcg.io/swsh12pt5gg/logo.png",
    "Majestic Dawn":  "https://images.pokemontcg.io/dp5/logo.png",
    "Crystal Guardians":  "https://images.pokemontcg.io/ex14/logo.png",
    "Chilling Reign":  "https://images.pokemontcg.io/swsh6/logo.png",
    "Lost Thunder":  "https://images.pokemontcg.io/sm8/logo.png",
    "BREAKthrough":  "https://images.pokemontcg.io/xy8/logo.png",
    "HGSS Black Star Promos":  "https://images.pokemontcg.io/hsp/logo.png",
    "HS—Undaunted":  "https://images.pokemontcg.io/hgss3/logo.png",
    "Arceus":  "https://images.pokemontcg.io/pl4/logo.png",
    "Emerald":  "https://images.pokemontcg.io/ex9/logo.png",
    "HS—Unleashed":  "https://images.pokemontcg.io/hgss2/logo.png",
    "Sandstorm":  "https://images.pokemontcg.io/ex2/logo.png",
    "Skyridge":  "https://images.pokemontcg.io/ecard3/logo.png",
    "Brilliant Stars":  "https://images.pokemontcg.io/swsh9/logo.png",
    "Guardians Rising":  "https://images.pokemontcg.io/sm2/logo.png",
    "Prismatic Evolutions":  "https://images.pokemontcg.io/sv8pt5/logo.png",
    "POP Series 2":  "https://images.pokemontcg.io/pop2/logo.png",
    "Neo Genesis":  "https://images.pokemontcg.io/neo1/logo.png",
    "Flashfire":  "https://images.pokemontcg.io/xy2/logo.png",
    "Crimson Invasion":  "https://images.pokemontcg.io/sm4/logo.png",
    "Fusion Strike":  "https://images.pokemontcg.io/swsh8/logo.png",
    "Team Rocket":  "https://images.pokemontcg.io/base5/logo.png",
    "Fossil":  "https://images.pokemontcg.io/base3/logo.png",
    "Stormfront":  "https://images.pokemontcg.io/dp7/logo.png",
    "Gym Heroes":  "https://images.pokemontcg.io/gym1/logo.png",
    "Great Encounters":  "https://images.pokemontcg.io/dp4/logo.png",
    "Astral Radiance":  "https://images.pokemontcg.io/swsh10/logo.png",
    "Legendary Collection":  "https://images.pokemontcg.io/base6/logo.png",
    "McDonald\u0027s Collection 2011":  "https://images.pokemontcg.io/mcd11/logo.png",
    "McDonald\u0027s Collection 2016":  "https://images.pokemontcg.io/mcd16/logo.png",
    "Mega Evolution":  "https://images.pokemontcg.io/me1/logo.png",
    "Ultra Prism":  "https://images.pokemontcg.io/sm5/logo.png",
    "Cosmic Eclipse":  "https://images.pokemontcg.io/sm12/logo.png",
    "Pokémon GO":  "https://images.pokemontcg.io/pgo/logo.png",
    "Brilliant Stars Trainer Gallery":  "https://images.pokemontcg.io/swsh9tg/logo.png",
    "Silver Tempest":  "https://images.pokemontcg.io/swsh12/logo.png",
    "POP Series 6":  "https://images.pokemontcg.io/pop6/logo.png",
    "Journey Together":  "https://images.pokemontcg.io/sv9/logo.png",
    "Pokémon Futsal Collection":  "https://images.pokemontcg.io/fut20/logo.png",
    "Generations":  "https://images.pokemontcg.io/g1/logo.png",
    "McDonald\u0027s Collection 2019":  "https://images.pokemontcg.io/mcd19/logo.png",
    "Unbroken Bonds":  "https://images.pokemontcg.io/sm10/logo.png",
    "Perfect Order":  "https://images.scrydex.com/pokemon/me3-logo/logo",
    "Hidden Fates Shiny Vault":  "https://images.pokemontcg.io/sma/logo.png",
    "Darkness Ablaze":  "https://images.pokemontcg.io/swsh3/logo.png",
    "Fates Collide":  "https://images.pokemontcg.io/xy10/logo.png",
    "McDonald\u0027s Collection 2015":  "https://images.pokemontcg.io/mcd15/logo.png",
    "Unseen Forces":  "https://images.pokemontcg.io/ex10/logo.png",
    "Forbidden Light":  "https://images.pokemontcg.io/sm6/logo.png",
    "Sun \u0026 Moon":  "https://images.pokemontcg.io/sm1/logo.png",
    "Legends Awakened":  "https://images.pokemontcg.io/dp6/logo.png",
    "Aquapolis":  "https://images.pokemontcg.io/ecard2/logo.png",
    "Primal Clash":  "https://images.pokemontcg.io/xy5/logo.png",
    "Shrouded Fable":  "https://images.pokemontcg.io/sv6pt5/logo.png",
    "Delta Species":  "https://images.pokemontcg.io/ex11/logo.png",
    "Kalos Starter Set":  "https://images.pokemontcg.io/xy0/logo.png",
    "Team Rocket Returns":  "https://images.pokemontcg.io/ex7/logo.png",
    "POP Series 4":  "https://images.pokemontcg.io/pop4/logo.png",
    "Supreme Victors":  "https://images.pokemontcg.io/pl3/logo.png",
    "McDonald\u0027s Collection 2021":  "https://images.pokemontcg.io/mcd21/logo.png",
    "Scarlet \u0026 Violet":  "https://images.pokemontcg.io/sv1/logo.png",
    "Rebel Clash":  "https://images.pokemontcg.io/swsh2/logo.png",
    "Temporal Forces":  "https://images.pokemontcg.io/sv5/logo.png",
    "POP Series 5":  "https://images.pokemontcg.io/pop5/logo.png",
    "Lost Origin Trainer Gallery":  "https://images.pokemontcg.io/swsh11tg/logo.png",
    "Battle Styles":  "https://images.pokemontcg.io/swsh5/logo.png",
    "DP Black Star Promos":  "https://images.pokemontcg.io/dpp/logo.png",
    "Dragon Frontiers":  "https://images.pokemontcg.io/ex15/logo.png",
    "Neo Revelation":  "https://images.pokemontcg.io/neo3/logo.png",
    "Crown Zenith":  "https://images.pokemontcg.io/swsh12pt5/logo.png",
    "Dragon Majesty":  "https://images.pokemontcg.io/sm75/logo.png",
    "Ascended Heroes":  "https://images.scrydex.com/pokemon/me2pt5-logo/logo",
    "Phantom Forces":  "https://images.pokemontcg.io/xy4/logo.png",
    "Silver Tempest Trainer Gallery":  "https://images.pokemontcg.io/swsh12tg/logo.png",
    "Platinum":  "https://images.pokemontcg.io/pl1/logo.png",
    "POP Series 7":  "https://images.pokemontcg.io/pop7/logo.png",
    "Hidden Fates":  "https://images.pokemontcg.io/sm115/logo.png",
    "Shining Fates Shiny Vault":  "https://images.pokemontcg.io/swsh45sv/logo.png",
    "Emerging Powers":  "https://images.pokemontcg.io/bw2/logo.png",
    "Celestial Storm":  "https://images.pokemontcg.io/sm7/logo.png",
    "Black Bolt":  "https://images.pokemontcg.io/zsv10pt5/logo.png",
    "Mysterious Treasures":  "https://images.pokemontcg.io/dp2/logo.png",
    "151":  "https://images.pokemontcg.io/sv3pt5/logo.png",
    "EX Trainer Kit Latias":  "https://images.pokemontcg.io/tk1a/logo.png",
    "Holon Phantoms":  "https://images.pokemontcg.io/ex13/logo.png",
    "Hidden Legends":  "https://images.pokemontcg.io/ex5/logo.png",
    "Deoxys":  "https://images.pokemontcg.io/ex8/logo.png",
    "Diamond \u0026 Pearl":  "https://images.pokemontcg.io/dp1/logo.png",
    "SWSH Black Star Promos":  "https://images.pokemontcg.io/swshp/logo.png",
    "POP Series 9":  "https://images.pokemontcg.io/pop9/logo.png",
    "White Flare":  "https://images.pokemontcg.io/rsv10pt5/logo.png",
    "Scarlet \u0026 Violet Energies":  "https://images.pokemontcg.io/sve/logo.png",
    "SM Black Star Promos":  "https://images.pokemontcg.io/smp/logo.png",
    "Legendary Treasures":  "https://images.pokemontcg.io/bw11/logo.png",
    "EX Trainer Kit 2 Minun":  "https://images.pokemontcg.io/tk2b/logo.png",
    "Shining Fates":  "https://images.pokemontcg.io/swsh45/logo.png",
    "Base":  "https://images.pokemontcg.io/base1/logo.png"
};


const PACK_ORDER = [
    "Chaos Rising",
    "Perfect Order",
    "Ascended Heroes",
    "Phantasmal Flames",
    "Mega Evolution",
    "Black Bolt",
    "White Flare",
    "Destined Rivals",
    "Journey Together",
    "Prismatic Evolutions",
    "Surging Sparks",
    "Stellar Crown",
    "Shrouded Fable",
    "Twilight Masquerade",
    "Temporal Forces",
    "Paldean Fates",
    "Paradox Rift",
    "151",
    "Obsidian Flames",
    "Paldea Evolved",
    "Scarlet \u0026 Violet Energies",
    "Scarlet \u0026 Violet",
    "Crown Zenith",
    "Crown Zenith Galarian Gallery",
    "Scarlet \u0026 Violet Black Star Promos",
    "Silver Tempest",
    "Silver Tempest Trainer Gallery",
    "Lost Origin",
    "Lost Origin Trainer Gallery",
    "McDonald\u0027s Collection 2022",
    "Pokémon GO",
    "Astral Radiance",
    "Astral Radiance Trainer Gallery",
    "Brilliant Stars",
    "Brilliant Stars Trainer Gallery",
    "Fusion Strike",
    "Celebrations",
    "Celebrations: Classic Collection",
    "Evolving Skies",
    "Chilling Reign",
    "Battle Styles",
    "Shining Fates",
    "Shining Fates Shiny Vault",
    "McDonald\u0027s Collection 2021",
    "Vivid Voltage",
    "Champion\u0027s Path",
    "Pokémon Futsal Collection",
    "Darkness Ablaze",
    "Rebel Clash",
    "Sword \u0026 Shield",
    "SWSH Black Star Promos",
    "Cosmic Eclipse",
    "McDonald\u0027s Collection 2019",
    "Hidden Fates",
    "Hidden Fates Shiny Vault",
    "Unified Minds",
    "Unbroken Bonds",
    "Detective Pikachu",
    "Team Up",
    "Lost Thunder",
    "McDonald\u0027s Collection 2018",
    "Dragon Majesty",
    "Celestial Storm",
    "Forbidden Light",
    "Ultra Prism",
    "McDonald\u0027s Collection 2017",
    "Crimson Invasion",
    "Shining Legends",
    "Burning Shadows",
    "Guardians Rising",
    "Sun \u0026 Moon",
    "SM Black Star Promos",
    "Evolutions",
    "McDonald\u0027s Collection 2016",
    "Steam Siege",
    "Fates Collide",
    "Generations",
    "BREAKpoint",
    "McDonald\u0027s Collection 2015",
    "BREAKthrough",
    "Ancient Origins",
    "Roaring Skies",
    "Double Crisis",
    "Primal Clash",
    "Phantom Forces",
    "Furious Fists",
    "McDonald\u0027s Collection 2014",
    "Flashfire",
    "XY",
    "Kalos Starter Set",
    "Legendary Treasures",
    "XY Black Star Promos",
    "Plasma Blast",
    "Plasma Freeze",
    "Plasma Storm",
    "Boundaries Crossed",
    "Dragon Vault",
    "Dragons Exalted",
    "McDonald\u0027s Collection 2012",
    "Dark Explorers",
    "Next Destinies",
    "Noble Victories",
    "Emerging Powers",
    "McDonald\u0027s Collection 2011",
    "Black \u0026 White",
    "BW Black Star Promos",
    "Call of Legends",
    "HS—Triumphant",
    "HS—Undaunted",
    "HS—Unleashed",
    "HeartGold \u0026 SoulSilver",
    "HGSS Black Star Promos",
    "Pokémon Rumble",
    "Arceus",
    "Supreme Victors",
    "Rising Rivals",
    "POP Series 9",
    "Platinum",
    "Stormfront",
    "POP Series 8",
    "Legends Awakened",
    "Majestic Dawn",
    "POP Series 7",
    "Great Encounters",
    "Secret Wonders",
    "POP Series 6",
    "Mysterious Treasures",
    "Diamond \u0026 Pearl",
    "DP Black Star Promos",
    "POP Series 5",
    "Power Keepers",
    "Dragon Frontiers",
    "Crystal Guardians",
    "POP Series 4",
    "Holon Phantoms",
    "POP Series 3",
    "EX Trainer Kit 2 Plusle",
    "EX Trainer Kit 2 Minun",
    "Legend Maker",
    "Delta Species",
    "Unseen Forces",
    "POP Series 2",
    "Emerald",
    "Deoxys",
    "Team Rocket Returns",
    "FireRed \u0026 LeafGreen",
    "POP Series 1",
    "EX Trainer Kit Latias",
    "EX Trainer Kit Latios",
    "Hidden Legends",
    "Team Magma vs Team Aqua",
    "Dragon",
    "Nintendo Black Star Promos",
    "Sandstorm",
    "Ruby \u0026 Sapphire",
    "Skyridge",
    "Aquapolis",
    "Best of Game",
    "Expedition Base Set",
    "Legendary Collection",
    "Neo Destiny",
    "Neo Revelation",
    "Southern Islands",
    "Neo Discovery",
    "Neo Genesis",
    "Gym Challenge",
    "Gym Heroes",
    "Team Rocket",
    "Base Set 2",
    "Fossil",
    "Wizards Black Star Promos",
    "Jungle",
    "Base"
];
